name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: npm install -g @salesforce/cli

      - name: Verify CLI
        run: sf --version

      - name: Authenticate
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > authfile.txt
          sf org login sfdx-url \
            --sfdx-url-file authfile.txt \
            --alias SFDCinteviewPrep \
            --set-default

      - name: List Authenticated Orgs
        run: sf org list

      - name: Verify Project
        run: |
          pwd
          ls -la
          ls force-app
          cat sfdx-project.json

      - name: Validate Deployment
        run: |
          sf project deploy validate \
            --source-dir force-app \
            --target-org SFDCinteviewPrep

      - name: Deploy
        run: |
          sf project deploy start \
            --source-dir force-app \
            --target-org SFDCinteviewPrep \
            --wait 30